all: win64

win64:
	g++ main.cpp -o editor.exe "../src/Tools/ReaderStruct.cpp" -I"../include/" -I"../lib/BearLibTerminal/include/" -L"../lib/BearLibTerminal/Windows64/" -lBearLibTerminal && editor.exe